name: transaction_heatmap
description: "A new Flutter for representing the spends over the credit card in Github Heat Map Format."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter_translate:
  flutter_card_scanner_latest: ^1.0.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # For image assets
    - assets/icons/ # For icon assets,
    - assets/json/en.json
    - assets/images/dashboard/
